### ISSUE TITLE
Supervisor-assign can't be run midday

### ISSUE THREAD

**Issue by nohelix** [nohelix/Behavior-autoanalysis#13]
Currently overwrites all unassigned assignments with [File Name], tasks with [Task], and detail with [Detail].

Checking for and eliminating any lines with [] should work. 

Potential to speed up summerize: check if there is not an 'NA' on Assigned_file in the rat_archive and don't run for that rat. This means the spreadsheet only shows rats that have new runs and don't have assignments.

_Sorry this is written poorly._

**Comment by tofof** [comment]
Ok. Multiple pieces here.

[] `Supervisor summarize` does not correctly retain the current assignment information for rats that have not run today. This needs fixing first. At that point, `supervisor-assign` should be functioning correctly with no update, since it should just be writing back the existing assignments.
[] To be even safer (and easier to use) however, it may be simpler to just have summarize only even output rats without an assignment in the first place. `Supervisor-assign` would still need updating to then only do a partial update of `rat_archive`. **This option has the consequence of making it impossible to use the supervisor.xlsx workflow to update an assignment after it has been committed with supervisor-assign.**

**Comment by tofof** [comment]
The secondary concern about option 2 -- not being able to tell that all rats had received updated assignments -- is mostly obviated by the `assignments.xlsx` summary file. It's still possible for bad things to happen if a .mat file just doesn't get checked in, but I think this was actually always the case.
