### ISSUE TITLE
Weight change

### ISSUE THREAD

**Issue by nohelix** [nohelix/Behavior-autoanalysis#2]
Implement a check weight.

**Comment by tofof** [comment]
What is inadequate about https://github.com/nohelix/Behavior-autoanalysis/blob/main/main.R#L1169-L1255 ?

**Comment by nohelix** [comment]
That runs off of run_properties. When you change a weight and then want to check that the weight change is ok it would be nice to push the rat ID in a different way.
Can it be changed to take id as an argument that defults to run_properties$rat_name but can be overridden with an argument, i.e. Check_Weight("Purple1")

**Comment by tofof** [comment]
I don't understand. There is no way to "change a weight", only a way to provide the current weight when you import the run data (either by specifying it on undergraduate.R or by setting old_file to True).

That function can't be changed directly to one that takes a rat name to be run on demand:

- If `old_file` exists, it's stale at that point and doesn't reflect whether this rat is using old_file
- If `analysis$weight` exists, it's stale and doesn't reflect the rat that corresponds to an arbitrary name
- It can't simply be scoped to not use analysis, because one of the functions of check_weight is to create `analysis$weight_change` which would be meaningless on an arbitrary rat. 
- Checking weight depends on a date. Just checking the most recent date is redundant; it was checked already when that weight was added through one of the flows metioned above. Checking 'today' is not possible, because there's no guarantee there is a weight for today.

I don't see a way to refactor the code flow to remove the need to know a date, and as soon as you consider that requirement, it becomes clear that any check would be redundant to the one that happened already.

**Comment by tofof** [comment]
If you can clarify what weight you want checked against what other weights, we can see if it's possible to do. It would be best not to duplicate the code. It might be possible, but awkward, to hoist the actual math part to a helper function used by both the `check_weight()` that happens when adding a run and the `check_weight_on_demand()` you have in mind.

**Comment by tofof** [comment]
After discussion in person, we decided the best course of action was to fully remove runs with incorrect weights. 

Currently, adding a run is a destructive action in that it moves the assignment data from `rat_archive` to the `run_archive`, so once the run is removed the assignment data is lost. To facilitate fixing runs by removal and re-adding, we decided to double-buffer the assignment data.

#### Necessary changes
- Add a second set of assignment columns to rat_archive, i.e. the 'old' buffer
- Copy current assignment to the 'old' buffer prior to clearing the 'current' buffer
- Copy 'old' assignment back to 'current' buffer when using admin tools functionality to remove a run

**Comment by tofof** [comment]
Closed by b80f4891d95a747e66f8f4689d588b2e50cb2175
